# Generated by Django 4.2.11 on 2024-05-23 14:34

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('ground_location', models.CharField(choices=[('home', 'home'), ('away', 'away')], default='home', max_length=50)),
                ('umpire_1', models.CharField(blank=True, max_length=50, null=True)),
                ('umpire_2', models.CharField(blank=True, max_length=50, null=True)),
                ('weather', models.CharField(choices=[('1', 'sunny'), ('2', 'sunny spells'), ('3', 'windy'), ('4', 'showers'), ('5', 'heavy rain'), ('6', 'rain and sun'), ('7', 'cloudy'), ('8', 'overcast'), ('9', 'other')], default='0', max_length=30)),
                ('batting_first', models.CharField(choices=[('home', 'home'), ('away', 'away')], default='home', max_length=50)),
                ('overs', models.IntegerField(default=1)),
                ('result', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(blank=True, max_length=50)),
                ('home_ground', models.CharField(blank=True, max_length=50)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='team_logos/')),
            ],
        ),
        migrations.CreateModel(
            name='MatchTeamPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('match_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='match.match')),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='match.team')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='away_team',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='away_team', to='match.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_team',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='home_team', to='match.team'),
        ),
    ]
