# Generated by Django 4.2.11 on 2024-05-24 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0002_alter_match_ground_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='batting_first',
            field=models.CharField(blank=True, choices=[('home', 'home'), ('away', 'away')], default='home', max_length=50, null=True),
        ),
    ]
