# Generated by Django 4.2.11 on 2024-05-24 05:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('match', '0003_alter_match_batting_first'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to=settings.AUTH_USER_MODEL),
        ),
    ]
