# Generated by Django 4.2.11 on 2024-05-25 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0004_match_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
