# Generated by Django 4.2.11 on 2024-05-29 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0005_match_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(blank=True, default='scheduled', max_length=50, null=True),
        ),
    ]
