# Generated by Django 4.2.11 on 2024-06-01 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0006_alter_match_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='elected_to',
            field=models.CharField(blank=True, choices=[('bowl', 'Bowl'), ('bat', 'Bat')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='toss_winner',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
