# Generated by Django 4.2.11 on 2024-06-01 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0007_match_elected_to_match_toss_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='overs_per_bowler',
            field=models.IntegerField(default=1),
        ),
    ]
