# Generated by Django 4.2.11 on 2024-06-04 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0008_match_overs_per_bowler'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchteamplayer',
            name='batting_balls_faced',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='matchteamplayer',
            name='batting_fours',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='matchteamplayer',
            name='batting_runs_scored',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='matchteamplayer',
            name='batting_sixes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matchteamplayer',
            name='bowling_maiden_overs',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='matchteamplayer',
            name='bowling_noballs',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='matchteamplayer',
            name='bowling_overs',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='matchteamplayer',
            name='bowling_runs_conceded',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='matchteamplayer',
            name='bowling_wickets',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='matchteamplayer',
            name='bowling_wides',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='matchteamplayer',
            name='how_out',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='matchteamplayer',
            name='is_batted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='matchteamplayer',
            name='is_bowled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='matchteamplayer',
            name='people_involved',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
