# Generated by Django 4.2.11 on 2024-06-05 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0010_matchteamplayer_is_non_striker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchteamplayer',
            name='is_bowling',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
