# Generated by Django 4.2.11 on 2024-06-06 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0011_matchteamplayer_is_bowling'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchteamplayer',
            name='bowling_fours',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='matchteamplayer',
            name='bowling_sixes',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
