# Generated by Django 4.2.11 on 2024-06-24 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0015_matchteamplayer_batting_strike_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='is_streaming',
            field=models.BooleanField(default=False),
        ),
    ]
