# Generated by Django 4.2.11 on 2024-05-23 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BallByBall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onstrike', models.CharField(blank=True, max_length=30, null=True)),
                ('offstrike', models.CharField(blank=True, max_length=30, null=True)),
                ('bowler', models.CharField(blank=True, max_length=30, null=True)),
                ('over', models.IntegerField(blank=True, default=0, null=True)),
                ('ball_in_over', models.IntegerField(blank=True, default=0, null=True)),
                ('total_runs', models.IntegerField(blank=True, default=0, null=True)),
                ('total_wickets', models.IntegerField(blank=True, default=0, null=True)),
                ('how_out', models.CharField(blank=True, max_length=20, null=True)),
                ('people_involved', models.CharField(blank=True, max_length=30, null=True)),
                ('runs', models.IntegerField(blank=True, default=0, null=True)),
                ('extras', models.IntegerField(blank=True, default=0, null=True)),
                ('extras_type', models.CharField(blank=True, max_length=20, null=True)),
                ('innings', models.IntegerField(default=1)),
                ('match_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='match_id', to='match.match')),
            ],
        ),
    ]
