# Generated by Django 4.2.11 on 2024-06-07 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ballbyball',
            name='people_involved',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
