# Generated by Django 4.2.11 on 2024-06-08 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0002_alter_ballbyball_people_involved'),
    ]

    operations = [
        migrations.AddField(
            model_name='ballbyball',
            name='who_out',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
