# Generated by Django 4.2.11 on 2024-06-13 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0003_ballbyball_who_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='ballbyball',
            name='byes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='ballbyball',
            name='legbyes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='ballbyball',
            name='noBalls',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='ballbyball',
            name='runs_inover',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='ballbyball',
            name='total_extas',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='ballbyball',
            name='wickets_inover',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='ballbyball',
            name='wides',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
