# Generated by Django 4.2.11 on 2024-06-13 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0004_ballbyball_byes_ballbyball_legbyes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ballbyball',
            old_name='total_extas',
            new_name='total_extras',
        ),
    ]
