# Generated by Django 4.2.11 on 2024-05-23 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0001_initial'),
        ('accounts', '0006_user_batting_100s_user_batting_50s_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='current_team_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='match.team'),
        ),
    ]
